{
 "title": "Gordo servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(gordo_server_info{cluster=~\"$cluster\"}, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gordo_server_request_duration_seconds_count{cluster=~\"$cluster\",project=~\"$project\",status_code=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests per model",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gordo_server_request_duration_seconds_count{cluster=~\"$cluster\",project=~\"$project\",status_code=\"200\",model!=\"\"}[30s])",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gordo_server_request_duration_seconds_count{cluster=~\"$cluster\",project=~\"$project\",status_code!=\"200\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gordo_server_requests_total{cluster=~\"$cluster\",project=~\"$project\"}[1m])",
     "legendFormat": "HTTP {{ status_code }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(gordo_server_request_duration_seconds_sum{cluster=~\"$cluster\",project=~\"$project\",status_code=\"200\"}[1m])\n/\nrate(gordo_server_request_duration_seconds_count{cluster=~\"$cluster\",project=~\"$project\",status_code=\"200\"}[1m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=~\"$cluster\",container=\"gordoserver-$project\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container=\"gordoserver-$project\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}