{
 "title": "Machine details",
 "tags": [ "machine" ],
 "time": { "from": "2018-06-20T02:41:38.411Z", "to": "2019-05-28T12:14:18.285Z" },
 "templating": {
  "list": [
   {
    "name": "Machine",
    "query": "SHOW TAG VALUES WITH KEY = \"machine\" "
   },
   {
    "name": "Sensor",
    "query": "SHOW FIELD KEYS from \"model-input\""
   }
  ]
 },
 "panels": [
  {
   "title": "Training time resolution",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT dataset->>'resolution' FROM machine where name='$Machine';"
    }
   ]
  },
  {
   "title": "Model config",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select machine.model as Configuration from machine where name='$Machine'"
    }
   ]
  },
  {
   "title": "Training filter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT dataset ->> 'filter'  FROM machine where name='$Machine';"
    }
   ]
  },
  {
   "title": "Training duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT age(date(dataset->>'train_end_date'), date(dataset->>'train_start_date'))  FROM machine where name='$Machine';"
    }
   ]
  },
  {
   "title": "Metric scores - Explained variance",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "select jsonb_each.key as metric, jsonb_each.value as scores from machine, jsonb_each(machine.metadata->'machine-metadata'->'build-metadata'->'model'->'cross-validation'->'scores'->'explained-variance-score') where name='$Machine'"
    }
   ]
  },
  {
   "title": "Model Input",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model-input",
     "query": "SELECT mean(/^$Sensor$/) FROM \"model-input\" WHERE (\"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Model Output",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model-output",
     "query": "SELECT mean(/^$Sensor$/)  FROM \"model-output\" WHERE (\"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Tag Anomaly",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tag-anomaly-scaled",
     "query": "SELECT mean(/^$Sensor$/)  FROM \"tag-anomaly-scaled\" WHERE (\"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Anomaly",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total-anomaly",
     "query": "SELECT mean(*) FROM \"total-anomaly-scaled\" WHERE (\"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  }
 ]
}