# set the default branch
# default: empty, the default branch on GitHub
branch: master

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# search for requirement files
# default: True
# allowed: True, False
search: False

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:

  - requirements.in:
      update: all
      pin: False
  - requirements.txt:
      update: security
      pin: True

  - test_requirements.in:
      update: all
      pin: False
  - test_requirements.txt:
      update: security
      pin: True

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup-

# allow to close stale PRs
# default: True
close_prs: True
