# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats: all

python:
  version: 3.6
  install:
    - requirements: dev_requirements.txt
    - requirements: dev_requirements.in
    - requirements: requirements.txt
    - method: pip
      path: .
