FROM python:3.6.6-slim-stretch

RUN mkdir /data

# Copy source code
COPY . /code

# Install gordo-components
RUN cd /code && python setup.py install

# build.sh (build the model) as executable default command
RUN cp /code/build.sh /usr/bin/build \
    && chmod +x /usr/bin/build

CMD ["build"]
