FROM seldonio/seldon-core-s2i-python3

RUN mkdir /code

# Install requirements separately for improved docker caching
COPY requirements.txt /code/
RUN pip install -r /code/requirements.txt

COPY . /code

# Install gordo-components, packaged from earlier 'python setup.py sdist'
RUN pip install /code/dist/$(ls /code/dist | head -1)
