FROM python:3.6.9 as builder

# Copy source code
COPY . /code
# Copy .git to deduce version number
COPY .git /code/

WORKDIR /code
RUN rm -rf /code/dist \
    && python setup.py sdist \
    && mv /code/dist/$(ls /code/dist | head -1) /code/dist/gordo-components-packed.tar.gz

# Extract a few big dependencies which docker will cache even when other dependencies change
RUN cat /code/requirements.txt | grep tensorflow== > /code/prereq.txt \
    && cat /code/requirements.txt | grep pyarrow== >> /code/prereq.txt \
    && cat /code/requirements.txt | grep scipy== >> /code/prereq.txt \
    && cat /code/requirements.txt | grep catboost== >> /code/prereq.txt

FROM python:3.6.9-slim-stretch

# Install requirements separately for improved docker caching
COPY --from=builder /code/prereq.txt .
RUN pip install --no-deps -r prereq.txt --no-cache-dir

COPY requirements.txt /code/
RUN pip install -r /code/requirements.txt --no-cache-dir



# Install gordo-components, packaged from earlier 'python setup.py sdist'
COPY --from=builder /code/dist/gordo-components-packed.tar.gz .

# Install gordo-components, packaged from earlier 'python setup.py sdist'
RUN pip install ./gordo-components-packed.tar.gz

CMD ["gordo-components", "run-server"]
