FROM python:3.6.9 as builder

# Copy source code
COPY . /code
# Copy .git to deduce version number
COPY .git /code/

WORKDIR /code
RUN rm -rf /code/dist \
    && python setup.py sdist \
    && mv /code/dist/$(ls /code/dist | head -1) /code/dist/gordo-components-packed.tar.gz

FROM python:3.6.9-slim-stretch

# Install requirements separately for improved docker caching
COPY requirements.txt /code/
RUN pip install -r /code/requirements.txt

# Install gordo-components, packaged from earlier 'python setup.py sdist'
COPY --from=builder /code/dist/gordo-components-packed.tar.gz .

# Install gordo-components, packaged from earlier 'python setup.py sdist'
RUN pip install ./gordo-components-packed.tar.gz

CMD ["gordo-components", "run-server", "--host", "0.0.0.0", "--port", "5555"]
