# Influx connection config secrets
apiVersion: v1
kind: Secret
metadata:
  name: src-influx-credentials
type: Opaque
data:
  # Literally, base64 'not-so-secret', because this is NOT a real secret
  api-key: bm90LXNvLXNlY3JldAo=
  api-key-header: bm90LXNvLXNlY3JldAo=
  database: bm90LXNvLXNlY3JldAo=
  host: bm90LXNvLXNlY3JldAo=
  measurement: bm90LXNvLXNlY3JldAo=
  password: bm90LXNvLXNlY3JldAo=
  path: bm90LXNvLXNlY3JldAo=
  port: bm90LXNvLXNlY3JldAo=
  username: bm90LXNvLXNlY3JldAo=
