apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
