apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submit-workflows-role
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submit-workflows-role
subjects:
- kind: ServiceAccount
  name: gordo-workflow-runner
