apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gordo-controller
  name: gordo-controller
spec:
  selector:
    matchLabels:
      app: gordo-controller
  template:
    metadata:
      labels:
        app: gordo-controller
    spec:
      containers:
      - image: docker.io/equinor/gordo-controller:0.1.1
        imagePullPolicy: Always
        name: gordo-controller
