name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        component: [builder, cli, client, machine, reporters, serializer, server, util, workflow, formatting, allelse]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-new-${{ hashFiles('requirements/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-new-

      - name: Install
        run: |
          pip install --upgrade "pip>=22.2.2,<23.0.0"
          pip install -r requirements/full_requirements.txt
          pip install -r requirements/test_requirements.txt

      - name: Test ${{ matrix.component }}
        run: python setup.py test${{ matrix.component }}
